template = "https://github.com/giellalt/template-lang-und"
rev_id = 318
template_sha = "71a1af4cb1cb80e9b86b2e9d1c090f473b0d8270"

[replacements]
__GLOTTOLOG_ID__ = "skol1241"
__REPO__ = "lang-sms"
__UND2C__ = "sms"
__UNDEFINED__ = "Skolt Sami"
__UND__ = "sms"
