template = "https://github.com/giellalt/template-lang-und"
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "skol1241"
__REPO__ = "lang-sms"
__UND2C__ = "sms"
__UNDEFINED__ = "Skolt Sami"
__UND__ = "sms"
