template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "skol1241"
__REPO__ = "lang-sms"
__UND2C__ = "sms"
__UNDEFINED__ = "Skolt Sami"
__UND__ = "sms"
