[package]
name = "sms"
human_name = "Skolt Sami"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.sms]
filename = "sms-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-sms"
platform = "windows"
uuid = "D0F37838-FE87-464A-A464-EDE35C90BCC7"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.sms"
package = "speller-sms"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-sms-mso"
platform = "windows"
uuid = "7D034B1F-3612-4C03-93AA-92C3EC4F2D99"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-sms"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
